{
	// setServoPosition
	sb.setServoPosition(sb.servo(SBServo.ServoA), 100)
	sb.setServoPosition(sb.servo(SBServo.ServoB), 100)
	sb.setServoPosition(sb.servo(SBServo.ServoC), 100)
	basic.pause(1000)
	sb.setServoPosition(sb.servo(SBServo.ServoA), 0)
	sb.setServoPosition(sb.servo(SBServo.ServoB), 0)
	sb.setServoPosition(sb.servo(SBServo.ServoC), 0)
	basic.pause(1000)

	// transitionServoPosition
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.Linear))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.Linear))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.SineIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.SineIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.SineOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.SineOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.SineInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.SineInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuadIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuadIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuadOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuadOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuadInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuadInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.CubicIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.CubicIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.CubicOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.CubicOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.CubicInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.CubicInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuartIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuartIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuartOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuartOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuartInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuartInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuintIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuintIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuintOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuintOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.QuintInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.QuintInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.ExpoIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.ExpoIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.ExpoOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.ExpoOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.ExpoInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.ExpoInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.CircIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.CircIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.CircOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.CircOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.CircInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.CircInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.BackOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.BackOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.BackInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.BackInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.ElasticIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.ElasticIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.ElasticOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.ElasticOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.ElasticInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.ElasticInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.BounceIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.BounceIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.BounceOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.BounceOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA),   0, 1, sb.easing(SBEasing.BounceInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoA), 100, 1, sb.easing(SBEasing.BounceInOut))

	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.Linear))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.Linear))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.SineIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.SineIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.SineOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.SineOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.SineInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.SineInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuadIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuadIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuadOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuadOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuadInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuadInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.CubicIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.CubicIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.CubicOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.CubicOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.CubicInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.CubicInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuartIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuartIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuartOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuartOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuartInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuartInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuintIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuintIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuintOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuintOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.QuintInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.QuintInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.ExpoIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.ExpoIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.ExpoOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.ExpoOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.ExpoInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.ExpoInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.CircIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.CircIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.CircOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.CircOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.CircInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.CircInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.BackOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.BackOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.BackInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.BackInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.ElasticIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.ElasticIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.ElasticOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.ElasticOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.ElasticInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.ElasticInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.BounceIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.BounceIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.BounceOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.BounceOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB),   0, 1, sb.easing(SBEasing.BounceInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoB), 100, 1, sb.easing(SBEasing.BounceInOut))

	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.Linear))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.Linear))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.SineIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.SineIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.SineOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.SineOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.SineInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.SineInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuadIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuadIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuadOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuadOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuadInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuadInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.CubicIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.CubicIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.CubicOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.CubicOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.CubicInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.CubicInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuartIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuartIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuartOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuartOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuartInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuartInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuintIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuintIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuintOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuintOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.QuintInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.QuintInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.ExpoIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.ExpoIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.ExpoOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.ExpoOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.ExpoInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.ExpoInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.CircIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.CircIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.CircOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.CircOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.CircInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.CircInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.BackOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.BackOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.BackInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.BackInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.ElasticIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.ElasticIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.ElasticOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.ElasticOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.ElasticInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.ElasticInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.BounceIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.BounceIn))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.BounceOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.BounceOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC),   0, 1, sb.easing(SBEasing.BounceInOut))
	sb.transitionServoPosition(sb.servo(SBServo.ServoC), 100, 1, sb.easing(SBEasing.BounceInOut))

	// setContinuousServoSpeed
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoA), -100)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoB), -100)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoC), -100)
	basic.pause(1000)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoA), 0)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoB), 0)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoC), 0)
	basic.pause(1000)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoA), 100)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoB), 100)
	sb.setContinuousServoSpeed(sb.servo(SBServo.ServoC), 100)
	basic.pause(1000)

	// turnOffServo
	sb.turnOffServo(sb.servo(SBServo.ServoA))
	sb.turnOffServo(sb.servo(SBServo.ServoB))
	sb.turnOffServo(sb.servo(SBServo.ServoC))
	basic.pause(1000)

	// setRgbLedColorRGB
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedA), 100, 0, 0)
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedB), 100, 0, 0)
	basic.pause(200)
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedA), 0, 100, 0)
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedB), 0, 100, 0)
	basic.pause(200)
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedA), 0, 0, 100)
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedB), 0, 0, 100)
	basic.pause(200)
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedA), 0, 0, 0)
	sb.setRgbLedColorRGB(sb.rgbLed(SBRgbLed.RgbLedB), 0, 0, 0)
	basic.pause(200)

	// setRgbLedColorHSB
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedA), 100, 0, 0)
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedB), 100, 0, 0)
	basic.pause(200)
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedA), 0, 100, 0)
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedB), 0, 100, 0)
	basic.pause(200)
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedA), 0, 0, 100)
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedB), 0, 0, 100)
	basic.pause(200)
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedA), 0, 0, 0)
	sb.setRgbLedColorHSB(sb.rgbLed(SBRgbLed.RgbLedB), 0, 0, 0)
	basic.pause(200)

	// setRgbLedColorHSB
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Red))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Red))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Orange))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Orange))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Yellow))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Yellow))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Green))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Green))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Blue))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Blue))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Indigo))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Indigo))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Violet))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Violet))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Purple))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Purple))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.White))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.White))
	basic.pause(200)
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedA), sb.color(SBColor.Black))
	sb.setRgbLedColor(sb.rgbLed(SBRgbLed.RgbLedB), sb.color(SBColor.Black))
}
